### ISSUE TITLE
再增加一个吧。

### ISSUE THREAD

**Issue by topsite** [JAM2199562/myopdiy#2]
https://github.com/hanwckf/immortalwrt-mt798x

**Comment by JAM2199562** [comment]
好，等237这个能正常编译以后吧，另外问下hanwckf这个是闭源驱动还是开源驱动？

**Comment by topsite** [comment]
> 好，等237这个能正常编译以后吧，另外问下hanwckf这个是闭源驱动还是开源驱动？

闭源驱动。

**Comment by JAM2199562** [comment]
增加好了
