### ISSUE TITLE
hanwckf不是说6000还没弄好呢？

### ISSUE THREAD

**Issue by lalasou** [JAM2199562/myopdiy#3]
感谢大佬脚本
为小白降低了n多门槛

等hanwckf那边完善好了
加上软件包  基本上就完美了
x-wrt 无线没有1024-QAM
不知道 闭源驱动有没有

**Comment by JAM2199562** [comment]
好像弄好了呀，后面打算软件包统一使用kiddin9的包

**Comment by lalasou** [comment]
> 好像弄好了呀，后面打算软件包统一使用kiddin9的包




没有吧  h大的地址不是在这呢？

https://github.com/hanwckf/immortalwrt-mt798x

h大博客  有说明
https://cmi.hanwckf.top/p/immortalwrt-mt798x/



我是小白  请大佬看看
我看最近更新内容不少

没看到红米6000配置文件  

**237的红米6000闭源固件挺好的就是有一个bug 5g 客户端之间 几乎没有速度 ，同5g下设备互传文件基本不能用 所以想让你试试hanwckf的闭源**

**Comment by JAM2199562** [comment]
> 

嗯嗯，确实是我看错了，AX6000还没弄好，等等呗，等他出来了弄一下很快的

**Comment by lalasou** [comment]
> > 
> 
> 
> 
> 嗯嗯，确实是我看错了，AX6000还没弄好，等等呗，等他出来了弄一下很快的

大佬已经适配ax6000

uboot 也有了

**Comment by JAM2199562** [comment]
> 

嗯，我来增加试试看
